{"name": "test_div[字符串除于正数异常用例]", "status": "passed", "parameters": [{"name": "a", "value": "'a'"}, {"name": "b", "value": "11"}, {"name": "expect", "value": "'TypeError'"}], "start": 1603368605839, "stop": 1603368605841, "uuid": "a6efb246-e95c-4f7e-9992-9e6f0d3593d8", "historyId": "6a710fef53b1259625c54ca524424703", "testCaseId": "1a86939ae8c138566bc6b8885470dbad", "fullName": "test_calc1.TestCalcTaskOne#test_div", "labels": [{"name": "tag", "value": "div"}, {"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_calc1"}, {"name": "subSuite", "value": "TestCalcTaskOne"}, {"name": "host", "value": "lingz-mac.lan"}, {"name": "thread", "value": "50460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc1"}]}