{"name": "test_div[字符串除于正数异常用例]", "status": "passed", "parameters": [{"name": "a", "value": "'a'"}, {"name": "b", "value": "11"}, {"name": "expect", "value": "'TypeError'"}], "start": 1603368606715, "stop": 1603368606715, "uuid": "dce5153d-2d13-4f50-abf6-418f230c0565", "historyId": "fbb8090006ab3e1e378aeab3247b7107", "testCaseId": "16b4d258933a2eed5be78e6101f1dc56", "fullName": "test_calc2.TestCalcTaskOne#test_div", "labels": [{"name": "tag", "value": "div"}, {"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_calc2"}, {"name": "subSuite", "value": "TestCalcTaskOne"}, {"name": "host", "value": "lingz-mac.lan"}, {"name": "thread", "value": "50460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc2"}]}