{"name": "test_div[aaa-34-TypeError]", "status": "passed", "parameters": [{"name": "a", "value": "'aaa'"}, {"name": "b", "value": "34"}, {"name": "expect", "value": "'TypeError'"}], "start": 1603031890609, "stop": 1603031890610, "uuid": "d97ca751-9e48-40ae-a6ac-d7829fc37f92", "historyId": "dc528e21ce459ee797a3dabb888920e4", "testCaseId": "4a57f615ae930c12d705a9fc7a66b88d", "fullName": "test_calc.TestCalc#test_div", "labels": [{"name": "story", "value": "计算器的除法"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "lingz-mac.lan"}, {"name": "thread", "value": "5761-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}