{"name": "test_div[小数除于字符串异常用例]", "status": "passed", "parameters": [{"name": "a", "value": "22.0"}, {"name": "b", "value": "'11'"}, {"name": "expect", "value": "'TypeError'"}], "start": 1603377910384, "stop": 1603377910385, "uuid": "e38f8455-7102-4aa2-a22d-d94d9aa66c9c", "historyId": "234ddac65658cee96db4496411b76139", "testCaseId": "1a86939ae8c138566bc6b8885470dbad", "fullName": "test_calc1.TestCalcTaskOne#test_div", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "div"}, {"name": "suite", "value": "test_calc1"}, {"name": "subSuite", "value": "TestCalcTaskOne"}, {"name": "host", "value": "lingz-mac.lan"}, {"name": "thread", "value": "2038-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc1"}]}