{"name": "test_div[小数除于字符串异常用例]", "status": "passed", "parameters": [{"name": "a", "value": "22.0"}, {"name": "b", "value": "'11'"}, {"name": "expect", "value": "'TypeError'"}], "start": 1603377912755, "stop": 1603377912757, "uuid": "6d24a9a7-f01f-4ea1-afda-886327c798b3", "historyId": "2b70520725a13fe98f463f6d1961013c", "testCaseId": "16b4d258933a2eed5be78e6101f1dc56", "fullName": "test_calc2.TestCalcTaskOne#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "tag", "value": "div"}, {"name": "suite", "value": "test_calc2"}, {"name": "subSuite", "value": "TestCalcTaskOne"}, {"name": "host", "value": "lingz-mac.lan"}, {"name": "thread", "value": "2038-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc2"}]}