{"name": "test_mult[小数乘于字符串异常用例]", "status": "passed", "parameters": [{"name": "a", "value": "22.0"}, {"name": "b", "value": "'11'"}, {"name": "expect", "value": "'TypeError'"}], "start": 1603377911776, "stop": 1603377911777, "uuid": "40a2d31a-46d4-4c4e-ac40-f0bd60827f62", "historyId": "4553734861c6aae11cd604d92613fb9b", "testCaseId": "46d692343060e5716c895bdf2d9d56eb", "fullName": "test_calc2.TestCalcTaskOne#test_mult", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "mult"}, {"name": "suite", "value": "test_calc2"}, {"name": "subSuite", "value": "TestCalcTaskOne"}, {"name": "host", "value": "lingz-mac.lan"}, {"name": "thread", "value": "2038-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc2"}]}